# Generated by Django 4.1.3 on 2025-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollCall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='capacity',
            new_name='course_capacity',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='establishment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
