# Generated by Django 4.1.3 on 2025-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollCall', '0002_rename_capacity_course_course_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
