# Generated by Django 4.1.3 on 2025-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollCall', '0006_qrattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yoklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='QRAttendance',
        ),
    ]
