# Generated by Django 4.1.3 on 2025-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollCall', '0007_yoklama_delete_qrattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoklama',
            name='onaylandi',
            field=models.BooleanField(default=False),
        ),
    ]
